version: "3.8"
services:
  db:
    image: mongo:6.0
    container_name: ${MONGO_DB_NAME}
    volumes:
      - poke-vol:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=project
    command: ['--auth']
  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_DB_NAME}
    ports:
      - 8080:8081
    restart: always
  
volumes:
  poke-vol:
    external: false
